spring.application.name=RateLimiterProject

spring.datasource.url=jdbc:postgresql://localhost:5432/RateLimiter
spring.datasource.username=postgres
spring.datasource.password=Rishit@5211
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=/api/v1

jwt.secret.Key=cbjdejdnwejnd328u832bcbd12rucbhebdy2g342y382cjh3e23njnwj